<?php
/**
 * BulkApi
 * PHP version 8.1
 *
 * @category Class
 * @package  ChurchTools
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ChurchTools REST API
 *
 * The ChurchTools REST API is the best entry point for developers to access ChurchTools. <br><br> **Authentication:** You need to be authorized to use some endpoints. Those endpoints are marked by a gray lock symbol. If you view the documentation, while you are logged into ChurchTools, all requests are already authorized. If you want to authorized a request, you need to provide a `Login Token` as `Authorization` header in the format `Authorization: Login <token>` or send a valid cookie. You can use the green \"Authorize\" dialog to enter those details and see how a request would look like in detail. <br><br> **Missing Endpoints:** Not all features are yet available by our new REST API. This documentation will grow in the future. We are working hard to add new endpoints with every ChurchTools version. The documentation will always show only those endpoints you can use with your ChurchTools installation.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@churchtools.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ChurchTools\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use ChurchTools\ApiException;
use ChurchTools\Configuration;
use ChurchTools\FormDataProcessor;
use ChurchTools\HeaderSelector;
use ChurchTools\ObjectSerializer;

/**
 * BulkApi Class Doc Comment
 *
 * @category Class
 * @package  ChurchTools
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BulkApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'postBulkjobs' => [
            'application/json',
        ],
        'postBulkjobsInfos' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation postBulkjobs
     *
     * Enqueue bulk job
     *
     * @param  string $domain_type type of job (required)
     * @param  string $job_key key of job (required)
     * @param  \ChurchTools\Model\PostBulkjobsRequest|null $post_bulkjobs_request post_bulkjobs_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postBulkjobs'] to see the possible values for this operation
     *
     * @throws \ChurchTools\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ChurchTools\Model\PostBulkjobs201Response|string
     */
    public function postBulkjobs($domain_type, $job_key, $post_bulkjobs_request = null, string $contentType = self::contentTypes['postBulkjobs'][0])
    {
        list($response) = $this->postBulkjobsWithHttpInfo($domain_type, $job_key, $post_bulkjobs_request, $contentType);
        return $response;
    }

    /**
     * Operation postBulkjobsWithHttpInfo
     *
     * Enqueue bulk job
     *
     * @param  string $domain_type type of job (required)
     * @param  string $job_key key of job (required)
     * @param  \ChurchTools\Model\PostBulkjobsRequest|null $post_bulkjobs_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postBulkjobs'] to see the possible values for this operation
     *
     * @throws \ChurchTools\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ChurchTools\Model\PostBulkjobs201Response|string, HTTP status code, HTTP response headers (array of strings)
     */
    public function postBulkjobsWithHttpInfo($domain_type, $job_key, $post_bulkjobs_request = null, string $contentType = self::contentTypes['postBulkjobs'][0])
    {
        $request = $this->postBulkjobsRequest($domain_type, $job_key, $post_bulkjobs_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        '\ChurchTools\Model\PostBulkjobs201Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        'string',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ChurchTools\Model\PostBulkjobs201Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ChurchTools\Model\PostBulkjobs201Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation postBulkjobsAsync
     *
     * Enqueue bulk job
     *
     * @param  string $domain_type type of job (required)
     * @param  string $job_key key of job (required)
     * @param  \ChurchTools\Model\PostBulkjobsRequest|null $post_bulkjobs_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postBulkjobs'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postBulkjobsAsync($domain_type, $job_key, $post_bulkjobs_request = null, string $contentType = self::contentTypes['postBulkjobs'][0])
    {
        return $this->postBulkjobsAsyncWithHttpInfo($domain_type, $job_key, $post_bulkjobs_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postBulkjobsAsyncWithHttpInfo
     *
     * Enqueue bulk job
     *
     * @param  string $domain_type type of job (required)
     * @param  string $job_key key of job (required)
     * @param  \ChurchTools\Model\PostBulkjobsRequest|null $post_bulkjobs_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postBulkjobs'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postBulkjobsAsyncWithHttpInfo($domain_type, $job_key, $post_bulkjobs_request = null, string $contentType = self::contentTypes['postBulkjobs'][0])
    {
        $returnType = '\ChurchTools\Model\PostBulkjobs201Response';
        $request = $this->postBulkjobsRequest($domain_type, $job_key, $post_bulkjobs_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postBulkjobs'
     *
     * @param  string $domain_type type of job (required)
     * @param  string $job_key key of job (required)
     * @param  \ChurchTools\Model\PostBulkjobsRequest|null $post_bulkjobs_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postBulkjobs'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postBulkjobsRequest($domain_type, $job_key, $post_bulkjobs_request = null, string $contentType = self::contentTypes['postBulkjobs'][0])
    {

        // verify the required parameter 'domain_type' is set
        if ($domain_type === null || (is_array($domain_type) && count($domain_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $domain_type when calling postBulkjobs'
            );
        }

        // verify the required parameter 'job_key' is set
        if ($job_key === null || (is_array($job_key) && count($job_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $job_key when calling postBulkjobs'
            );
        }



        $resourcePath = '/bulkjobs/{domainType}/{jobKey}/enqueue';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($domain_type !== null) {
            $resourcePath = str_replace(
                '{' . 'domainType' . '}',
                ObjectSerializer::toPathValue($domain_type),
                $resourcePath
            );
        }
        // path params
        if ($job_key !== null) {
            $resourcePath = str_replace(
                '{' . 'jobKey' . '}',
                ObjectSerializer::toPathValue($job_key),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'text/plain', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($post_bulkjobs_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($post_bulkjobs_request));
            } else {
                $httpBody = $post_bulkjobs_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postBulkjobsInfos
     *
     * Calculate infos about bulk job
     *
     * @param  string $domain_type type of job (required)
     * @param  string $job_key key of job (required)
     * @param  \ChurchTools\Model\PostBulkjobsInfosRequest|null $post_bulkjobs_infos_request post_bulkjobs_infos_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postBulkjobsInfos'] to see the possible values for this operation
     *
     * @throws \ChurchTools\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ChurchTools\Model\PostBulkjobsInfos200Response|string
     */
    public function postBulkjobsInfos($domain_type, $job_key, $post_bulkjobs_infos_request = null, string $contentType = self::contentTypes['postBulkjobsInfos'][0])
    {
        list($response) = $this->postBulkjobsInfosWithHttpInfo($domain_type, $job_key, $post_bulkjobs_infos_request, $contentType);
        return $response;
    }

    /**
     * Operation postBulkjobsInfosWithHttpInfo
     *
     * Calculate infos about bulk job
     *
     * @param  string $domain_type type of job (required)
     * @param  string $job_key key of job (required)
     * @param  \ChurchTools\Model\PostBulkjobsInfosRequest|null $post_bulkjobs_infos_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postBulkjobsInfos'] to see the possible values for this operation
     *
     * @throws \ChurchTools\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ChurchTools\Model\PostBulkjobsInfos200Response|string, HTTP status code, HTTP response headers (array of strings)
     */
    public function postBulkjobsInfosWithHttpInfo($domain_type, $job_key, $post_bulkjobs_infos_request = null, string $contentType = self::contentTypes['postBulkjobsInfos'][0])
    {
        $request = $this->postBulkjobsInfosRequest($domain_type, $job_key, $post_bulkjobs_infos_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\ChurchTools\Model\PostBulkjobsInfos200Response',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        'string',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\ChurchTools\Model\PostBulkjobsInfos200Response',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ChurchTools\Model\PostBulkjobsInfos200Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation postBulkjobsInfosAsync
     *
     * Calculate infos about bulk job
     *
     * @param  string $domain_type type of job (required)
     * @param  string $job_key key of job (required)
     * @param  \ChurchTools\Model\PostBulkjobsInfosRequest|null $post_bulkjobs_infos_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postBulkjobsInfos'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postBulkjobsInfosAsync($domain_type, $job_key, $post_bulkjobs_infos_request = null, string $contentType = self::contentTypes['postBulkjobsInfos'][0])
    {
        return $this->postBulkjobsInfosAsyncWithHttpInfo($domain_type, $job_key, $post_bulkjobs_infos_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postBulkjobsInfosAsyncWithHttpInfo
     *
     * Calculate infos about bulk job
     *
     * @param  string $domain_type type of job (required)
     * @param  string $job_key key of job (required)
     * @param  \ChurchTools\Model\PostBulkjobsInfosRequest|null $post_bulkjobs_infos_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postBulkjobsInfos'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postBulkjobsInfosAsyncWithHttpInfo($domain_type, $job_key, $post_bulkjobs_infos_request = null, string $contentType = self::contentTypes['postBulkjobsInfos'][0])
    {
        $returnType = '\ChurchTools\Model\PostBulkjobsInfos200Response';
        $request = $this->postBulkjobsInfosRequest($domain_type, $job_key, $post_bulkjobs_infos_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postBulkjobsInfos'
     *
     * @param  string $domain_type type of job (required)
     * @param  string $job_key key of job (required)
     * @param  \ChurchTools\Model\PostBulkjobsInfosRequest|null $post_bulkjobs_infos_request (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['postBulkjobsInfos'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postBulkjobsInfosRequest($domain_type, $job_key, $post_bulkjobs_infos_request = null, string $contentType = self::contentTypes['postBulkjobsInfos'][0])
    {

        // verify the required parameter 'domain_type' is set
        if ($domain_type === null || (is_array($domain_type) && count($domain_type) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $domain_type when calling postBulkjobsInfos'
            );
        }

        // verify the required parameter 'job_key' is set
        if ($job_key === null || (is_array($job_key) && count($job_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $job_key when calling postBulkjobsInfos'
            );
        }



        $resourcePath = '/bulkjobs/{domainType}/{jobKey}/infos';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($domain_type !== null) {
            $resourcePath = str_replace(
                '{' . 'domainType' . '}',
                ObjectSerializer::toPathValue($domain_type),
                $resourcePath
            );
        }
        // path params
        if ($job_key !== null) {
            $resourcePath = str_replace(
                '{' . 'jobKey' . '}',
                ObjectSerializer::toPathValue($job_key),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', 'text/plain', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($post_bulkjobs_infos_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($post_bulkjobs_infos_request));
            } else {
                $httpBody = $post_bulkjobs_infos_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
