<?php
/**
 * ExternalLogin
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ChurchTools
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ChurchTools REST API
 *
 * The ChurchTools REST API is the best entry point for developers to access ChurchTools. <br><br> **Authentication:** You need to be authorized to use some endpoints. Those endpoints are marked by a gray lock symbol. If you view the documentation, while you are logged into ChurchTools, all requests are already authorized. If you want to authorized a request, you need to provide a `Login Token` as `Authorization` header in the format `Authorization: Login <token>` or send a valid cookie. You can use the green \"Authorize\" dialog to enter those details and see how a request would look like in detail. <br><br> **Missing Endpoints:** Not all features are yet available by our new REST API. This documentation will grow in the future. We are working hard to add new endpoints with every ChurchTools version. The documentation will always show only those endpoints you can use with your ChurchTools installation.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@churchtools.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ChurchTools\Model;

use \ArrayAccess;
use \ChurchTools\ObjectSerializer;

/**
 * ExternalLogin Class Doc Comment
 *
 * @category Class
 * @package  ChurchTools
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ExternalLogin implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ExternalLogin';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'config' => 'mixed',
        'create_new_person' => 'bool',
        'name' => 'string',
        'new_person_campus_id' => 'int',
        'new_person_department_id' => 'int',
        'new_person_status_id' => 'int',
        'type' => 'string',
        'update_data_on_login' => 'bool',
        'id' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'config' => null,
        'create_new_person' => null,
        'name' => null,
        'new_person_campus_id' => null,
        'new_person_department_id' => null,
        'new_person_status_id' => null,
        'type' => null,
        'update_data_on_login' => null,
        'id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'config' => true,
        'create_new_person' => false,
        'name' => false,
        'new_person_campus_id' => false,
        'new_person_department_id' => false,
        'new_person_status_id' => false,
        'type' => false,
        'update_data_on_login' => false,
        'id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'config' => 'config',
        'create_new_person' => 'createNewPerson',
        'name' => 'name',
        'new_person_campus_id' => 'newPersonCampusId',
        'new_person_department_id' => 'newPersonDepartmentId',
        'new_person_status_id' => 'newPersonStatusId',
        'type' => 'type',
        'update_data_on_login' => 'updateDataOnLogin',
        'id' => 'id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'config' => 'setConfig',
        'create_new_person' => 'setCreateNewPerson',
        'name' => 'setName',
        'new_person_campus_id' => 'setNewPersonCampusId',
        'new_person_department_id' => 'setNewPersonDepartmentId',
        'new_person_status_id' => 'setNewPersonStatusId',
        'type' => 'setType',
        'update_data_on_login' => 'setUpdateDataOnLogin',
        'id' => 'setId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'config' => 'getConfig',
        'create_new_person' => 'getCreateNewPerson',
        'name' => 'getName',
        'new_person_campus_id' => 'getNewPersonCampusId',
        'new_person_department_id' => 'getNewPersonDepartmentId',
        'new_person_status_id' => 'getNewPersonStatusId',
        'type' => 'getType',
        'update_data_on_login' => 'getUpdateDataOnLogin',
        'id' => 'getId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('config', $data ?? [], null);
        $this->setIfExists('create_new_person', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('new_person_campus_id', $data ?? [], null);
        $this->setIfExists('new_person_department_id', $data ?? [], null);
        $this->setIfExists('new_person_status_id', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('update_data_on_login', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['new_person_campus_id'] === null) {
            $invalidProperties[] = "'new_person_campus_id' can't be null";
        }
        if ($this->container['new_person_department_id'] === null) {
            $invalidProperties[] = "'new_person_department_id' can't be null";
        }
        if ($this->container['new_person_status_id'] === null) {
            $invalidProperties[] = "'new_person_status_id' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets config
     *
     * @return mixed|null
     */
    public function getConfig()
    {
        return $this->container['config'];
    }

    /**
     * Sets config
     *
     * @param mixed|null $config config
     *
     * @return self
     */
    public function setConfig($config)
    {
        if (is_null($config)) {
            array_push($this->openAPINullablesSetToNull, 'config');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('config', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['config'] = $config;

        return $this;
    }

    /**
     * Gets create_new_person
     *
     * @return bool|null
     */
    public function getCreateNewPerson()
    {
        return $this->container['create_new_person'];
    }

    /**
     * Sets create_new_person
     *
     * @param bool|null $create_new_person create_new_person
     *
     * @return self
     */
    public function setCreateNewPerson($create_new_person)
    {
        if (is_null($create_new_person)) {
            throw new \InvalidArgumentException('non-nullable create_new_person cannot be null');
        }
        $this->container['create_new_person'] = $create_new_person;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets new_person_campus_id
     *
     * @return int
     */
    public function getNewPersonCampusId()
    {
        return $this->container['new_person_campus_id'];
    }

    /**
     * Sets new_person_campus_id
     *
     * @param int $new_person_campus_id new_person_campus_id
     *
     * @return self
     */
    public function setNewPersonCampusId($new_person_campus_id)
    {
        if (is_null($new_person_campus_id)) {
            throw new \InvalidArgumentException('non-nullable new_person_campus_id cannot be null');
        }
        $this->container['new_person_campus_id'] = $new_person_campus_id;

        return $this;
    }

    /**
     * Gets new_person_department_id
     *
     * @return int
     */
    public function getNewPersonDepartmentId()
    {
        return $this->container['new_person_department_id'];
    }

    /**
     * Sets new_person_department_id
     *
     * @param int $new_person_department_id new_person_department_id
     *
     * @return self
     */
    public function setNewPersonDepartmentId($new_person_department_id)
    {
        if (is_null($new_person_department_id)) {
            throw new \InvalidArgumentException('non-nullable new_person_department_id cannot be null');
        }
        $this->container['new_person_department_id'] = $new_person_department_id;

        return $this;
    }

    /**
     * Gets new_person_status_id
     *
     * @return int
     */
    public function getNewPersonStatusId()
    {
        return $this->container['new_person_status_id'];
    }

    /**
     * Sets new_person_status_id
     *
     * @param int $new_person_status_id new_person_status_id
     *
     * @return self
     */
    public function setNewPersonStatusId($new_person_status_id)
    {
        if (is_null($new_person_status_id)) {
            throw new \InvalidArgumentException('non-nullable new_person_status_id cannot be null');
        }
        $this->container['new_person_status_id'] = $new_person_status_id;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets update_data_on_login
     *
     * @return bool|null
     */
    public function getUpdateDataOnLogin()
    {
        return $this->container['update_data_on_login'];
    }

    /**
     * Sets update_data_on_login
     *
     * @param bool|null $update_data_on_login update_data_on_login
     *
     * @return self
     */
    public function setUpdateDataOnLogin($update_data_on_login)
    {
        if (is_null($update_data_on_login)) {
            throw new \InvalidArgumentException('non-nullable update_data_on_login cannot be null');
        }
        $this->container['update_data_on_login'] = $update_data_on_login;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


