<?php
/**
 * GetGroups200ResponseDataInnerInformation
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ChurchTools
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ChurchTools REST API
 *
 * The ChurchTools REST API is the best entry point for developers to access ChurchTools. <br><br> **Authentication:** You need to be authorized to use some endpoints. Those endpoints are marked by a gray lock symbol. If you view the documentation, while you are logged into ChurchTools, all requests are already authorized. If you want to authorized a request, you need to provide a `Login Token` as `Authorization` header in the format `Authorization: Login <token>` or send a valid cookie. You can use the green \"Authorize\" dialog to enter those details and see how a request would look like in detail. <br><br> **Missing Endpoints:** Not all features are yet available by our new REST API. This documentation will grow in the future. We are working hard to add new endpoints with every ChurchTools version. The documentation will always show only those endpoints you can use with your ChurchTools installation.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@churchtools.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ChurchTools\Model;

use \ArrayAccess;
use \ChurchTools\ObjectSerializer;

/**
 * GetGroups200ResponseDataInnerInformation Class Doc Comment
 *
 * @category Class
 * @package  ChurchTools
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetGroups200ResponseDataInnerInformation implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'get_groups_200_response_data_inner_information';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'age_group_ids' => 'int[]',
        'campus_id' => 'int',
        'chat_status' => 'string',
        'color' => 'string',
        'date_of_foundation' => '\DateTime',
        'end_date' => '\DateTime',
        'group_category_id' => 'int',
        'group_homepage_url' => 'string',
        'group_status_id' => 'int',
        'group_type_id' => 'int',
        'image_url' => 'string',
        'max_members' => 'int',
        'meeting_time' => 'string',
        'note' => 'string',
        'sign_up_override_role_id' => 'int',
        'target_group_id' => 'int',
        'weekday' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'age_group_ids' => null,
        'campus_id' => null,
        'chat_status' => null,
        'color' => null,
        'date_of_foundation' => 'date',
        'end_date' => 'date',
        'group_category_id' => null,
        'group_homepage_url' => null,
        'group_status_id' => null,
        'group_type_id' => null,
        'image_url' => null,
        'max_members' => null,
        'meeting_time' => null,
        'note' => null,
        'sign_up_override_role_id' => null,
        'target_group_id' => null,
        'weekday' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'age_group_ids' => false,
        'campus_id' => true,
        'chat_status' => false,
        'color' => true,
        'date_of_foundation' => true,
        'end_date' => true,
        'group_category_id' => true,
        'group_homepage_url' => true,
        'group_status_id' => true,
        'group_type_id' => true,
        'image_url' => true,
        'max_members' => true,
        'meeting_time' => true,
        'note' => true,
        'sign_up_override_role_id' => true,
        'target_group_id' => true,
        'weekday' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'age_group_ids' => 'ageGroupIds',
        'campus_id' => 'campusId',
        'chat_status' => 'chatStatus',
        'color' => 'color',
        'date_of_foundation' => 'dateOfFoundation',
        'end_date' => 'endDate',
        'group_category_id' => 'groupCategoryId',
        'group_homepage_url' => 'groupHomepageUrl',
        'group_status_id' => 'groupStatusId',
        'group_type_id' => 'groupTypeId',
        'image_url' => 'imageUrl',
        'max_members' => 'maxMembers',
        'meeting_time' => 'meetingTime',
        'note' => 'note',
        'sign_up_override_role_id' => 'signUpOverrideRoleId',
        'target_group_id' => 'targetGroupId',
        'weekday' => 'weekday'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'age_group_ids' => 'setAgeGroupIds',
        'campus_id' => 'setCampusId',
        'chat_status' => 'setChatStatus',
        'color' => 'setColor',
        'date_of_foundation' => 'setDateOfFoundation',
        'end_date' => 'setEndDate',
        'group_category_id' => 'setGroupCategoryId',
        'group_homepage_url' => 'setGroupHomepageUrl',
        'group_status_id' => 'setGroupStatusId',
        'group_type_id' => 'setGroupTypeId',
        'image_url' => 'setImageUrl',
        'max_members' => 'setMaxMembers',
        'meeting_time' => 'setMeetingTime',
        'note' => 'setNote',
        'sign_up_override_role_id' => 'setSignUpOverrideRoleId',
        'target_group_id' => 'setTargetGroupId',
        'weekday' => 'setWeekday'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'age_group_ids' => 'getAgeGroupIds',
        'campus_id' => 'getCampusId',
        'chat_status' => 'getChatStatus',
        'color' => 'getColor',
        'date_of_foundation' => 'getDateOfFoundation',
        'end_date' => 'getEndDate',
        'group_category_id' => 'getGroupCategoryId',
        'group_homepage_url' => 'getGroupHomepageUrl',
        'group_status_id' => 'getGroupStatusId',
        'group_type_id' => 'getGroupTypeId',
        'image_url' => 'getImageUrl',
        'max_members' => 'getMaxMembers',
        'meeting_time' => 'getMeetingTime',
        'note' => 'getNote',
        'sign_up_override_role_id' => 'getSignUpOverrideRoleId',
        'target_group_id' => 'getTargetGroupId',
        'weekday' => 'getWeekday'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const CHAT_STATUS_NOT_STARTED = 'NOT_STARTED';
    public const CHAT_STATUS_STARTING = 'STARTING';
    public const CHAT_STATUS_STARTED = 'STARTED';
    public const CHAT_STATUS_STOPPED = 'STOPPED';
    public const COLOR_ACCENT = 'accent';
    public const COLOR_AMBER = 'amber';
    public const COLOR_BASIC = 'basic';
    public const COLOR_BLUE = 'blue';
    public const COLOR_CRITICAL = 'critical';
    public const COLOR_CONSTRUCTIVE = 'constructive';
    public const COLOR_CYAN = 'cyan';
    public const COLOR_EMERALD = 'emerald';
    public const COLOR_ERROR = 'error';
    public const COLOR_FUCHSIA = 'fuchsia';
    public const COLOR_GREEN = 'green';
    public const COLOR_INDIGO = 'indigo';
    public const COLOR_INFO = 'info';
    public const COLOR_LIME = 'lime';
    public const COLOR_MAGIC = 'magic';
    public const COLOR_ORANGE = 'orange';
    public const COLOR_PINK = 'pink';
    public const COLOR_PURPLE = 'purple';
    public const COLOR_RED = 'red';
    public const COLOR_ROSE = 'rose';
    public const COLOR_SKY = 'sky';
    public const COLOR_SUCCESS = 'success';
    public const COLOR_TEAL = 'teal';
    public const COLOR_VIOLET = 'violet';
    public const COLOR_WARNING = 'warning';
    public const COLOR_YELLOW = 'yellow';
    public const COLOR_DESTRUCTIVE = 'destructive';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getChatStatusAllowableValues()
    {
        return [
            self::CHAT_STATUS_NOT_STARTED,
            self::CHAT_STATUS_STARTING,
            self::CHAT_STATUS_STARTED,
            self::CHAT_STATUS_STOPPED,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getColorAllowableValues()
    {
        return [
            self::COLOR_ACCENT,
            self::COLOR_AMBER,
            self::COLOR_BASIC,
            self::COLOR_BLUE,
            self::COLOR_CRITICAL,
            self::COLOR_CONSTRUCTIVE,
            self::COLOR_CYAN,
            self::COLOR_EMERALD,
            self::COLOR_ERROR,
            self::COLOR_FUCHSIA,
            self::COLOR_GREEN,
            self::COLOR_INDIGO,
            self::COLOR_INFO,
            self::COLOR_LIME,
            self::COLOR_MAGIC,
            self::COLOR_ORANGE,
            self::COLOR_PINK,
            self::COLOR_PURPLE,
            self::COLOR_RED,
            self::COLOR_ROSE,
            self::COLOR_SKY,
            self::COLOR_SUCCESS,
            self::COLOR_TEAL,
            self::COLOR_VIOLET,
            self::COLOR_WARNING,
            self::COLOR_YELLOW,
            self::COLOR_DESTRUCTIVE,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('age_group_ids', $data ?? [], null);
        $this->setIfExists('campus_id', $data ?? [], null);
        $this->setIfExists('chat_status', $data ?? [], null);
        $this->setIfExists('color', $data ?? [], null);
        $this->setIfExists('date_of_foundation', $data ?? [], null);
        $this->setIfExists('end_date', $data ?? [], null);
        $this->setIfExists('group_category_id', $data ?? [], null);
        $this->setIfExists('group_homepage_url', $data ?? [], null);
        $this->setIfExists('group_status_id', $data ?? [], null);
        $this->setIfExists('group_type_id', $data ?? [], null);
        $this->setIfExists('image_url', $data ?? [], null);
        $this->setIfExists('max_members', $data ?? [], null);
        $this->setIfExists('meeting_time', $data ?? [], null);
        $this->setIfExists('note', $data ?? [], null);
        $this->setIfExists('sign_up_override_role_id', $data ?? [], null);
        $this->setIfExists('target_group_id', $data ?? [], null);
        $this->setIfExists('weekday', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['age_group_ids'] === null) {
            $invalidProperties[] = "'age_group_ids' can't be null";
        }
        if ($this->container['campus_id'] === null) {
            $invalidProperties[] = "'campus_id' can't be null";
        }
        if ($this->container['chat_status'] === null) {
            $invalidProperties[] = "'chat_status' can't be null";
        }
        $allowedValues = $this->getChatStatusAllowableValues();
        if (!is_null($this->container['chat_status']) && !in_array($this->container['chat_status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'chat_status', must be one of '%s'",
                $this->container['chat_status'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['color'] === null) {
            $invalidProperties[] = "'color' can't be null";
        }
        $allowedValues = $this->getColorAllowableValues();
        if (!is_null($this->container['color']) && !in_array($this->container['color'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'color', must be one of '%s'",
                $this->container['color'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['date_of_foundation'] === null) {
            $invalidProperties[] = "'date_of_foundation' can't be null";
        }
        if ($this->container['end_date'] === null) {
            $invalidProperties[] = "'end_date' can't be null";
        }
        if ($this->container['group_category_id'] === null) {
            $invalidProperties[] = "'group_category_id' can't be null";
        }
        if ($this->container['group_homepage_url'] === null) {
            $invalidProperties[] = "'group_homepage_url' can't be null";
        }
        if ($this->container['group_status_id'] === null) {
            $invalidProperties[] = "'group_status_id' can't be null";
        }
        if ($this->container['group_type_id'] === null) {
            $invalidProperties[] = "'group_type_id' can't be null";
        }
        if ($this->container['image_url'] === null) {
            $invalidProperties[] = "'image_url' can't be null";
        }
        if ($this->container['max_members'] === null) {
            $invalidProperties[] = "'max_members' can't be null";
        }
        if ($this->container['meeting_time'] === null) {
            $invalidProperties[] = "'meeting_time' can't be null";
        }
        if ($this->container['note'] === null) {
            $invalidProperties[] = "'note' can't be null";
        }
        if ($this->container['sign_up_override_role_id'] === null) {
            $invalidProperties[] = "'sign_up_override_role_id' can't be null";
        }
        if ($this->container['target_group_id'] === null) {
            $invalidProperties[] = "'target_group_id' can't be null";
        }
        if ($this->container['weekday'] === null) {
            $invalidProperties[] = "'weekday' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets age_group_ids
     *
     * @return int[]
     */
    public function getAgeGroupIds()
    {
        return $this->container['age_group_ids'];
    }

    /**
     * Sets age_group_ids
     *
     * @param int[] $age_group_ids age_group_ids
     *
     * @return self
     */
    public function setAgeGroupIds($age_group_ids)
    {
        if (is_null($age_group_ids)) {
            throw new \InvalidArgumentException('non-nullable age_group_ids cannot be null');
        }
        $this->container['age_group_ids'] = $age_group_ids;

        return $this;
    }

    /**
     * Gets campus_id
     *
     * @return int
     */
    public function getCampusId()
    {
        return $this->container['campus_id'];
    }

    /**
     * Sets campus_id
     *
     * @param int $campus_id campus_id
     *
     * @return self
     */
    public function setCampusId($campus_id)
    {
        if (is_null($campus_id)) {
            array_push($this->openAPINullablesSetToNull, 'campus_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('campus_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['campus_id'] = $campus_id;

        return $this;
    }

    /**
     * Gets chat_status
     *
     * @return string
     */
    public function getChatStatus()
    {
        return $this->container['chat_status'];
    }

    /**
     * Sets chat_status
     *
     * @param string $chat_status status of chat room
     *
     * @return self
     */
    public function setChatStatus($chat_status)
    {
        if (is_null($chat_status)) {
            throw new \InvalidArgumentException('non-nullable chat_status cannot be null');
        }
        $allowedValues = $this->getChatStatusAllowableValues();
        if (!in_array($chat_status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'chat_status', must be one of '%s'",
                    $chat_status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['chat_status'] = $chat_status;

        return $this;
    }

    /**
     * Gets color
     *
     * @return string
     */
    public function getColor()
    {
        return $this->container['color'];
    }

    /**
     * Sets color
     *
     * @param string $color A color in ChurchTools
     *
     * @return self
     */
    public function setColor($color)
    {
        if (is_null($color)) {
            array_push($this->openAPINullablesSetToNull, 'color');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('color', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getColorAllowableValues();
        if (!is_null($color) && !in_array($color, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'color', must be one of '%s'",
                    $color,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['color'] = $color;

        return $this;
    }

    /**
     * Gets date_of_foundation
     *
     * @return \DateTime
     */
    public function getDateOfFoundation()
    {
        return $this->container['date_of_foundation'];
    }

    /**
     * Sets date_of_foundation
     *
     * @param \DateTime $date_of_foundation A simple date in ISO format, e.g. '2022-10-19'
     *
     * @return self
     */
    public function setDateOfFoundation($date_of_foundation)
    {
        if (is_null($date_of_foundation)) {
            array_push($this->openAPINullablesSetToNull, 'date_of_foundation');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date_of_foundation', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date_of_foundation'] = $date_of_foundation;

        return $this;
    }

    /**
     * Gets end_date
     *
     * @return \DateTime
     */
    public function getEndDate()
    {
        return $this->container['end_date'];
    }

    /**
     * Sets end_date
     *
     * @param \DateTime $end_date A simple date in ISO format, e.g. '2022-10-19'
     *
     * @return self
     */
    public function setEndDate($end_date)
    {
        if (is_null($end_date)) {
            array_push($this->openAPINullablesSetToNull, 'end_date');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('end_date', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['end_date'] = $end_date;

        return $this;
    }

    /**
     * Gets group_category_id
     *
     * @return int
     */
    public function getGroupCategoryId()
    {
        return $this->container['group_category_id'];
    }

    /**
     * Sets group_category_id
     *
     * @param int $group_category_id group_category_id
     *
     * @return self
     */
    public function setGroupCategoryId($group_category_id)
    {
        if (is_null($group_category_id)) {
            array_push($this->openAPINullablesSetToNull, 'group_category_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('group_category_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['group_category_id'] = $group_category_id;

        return $this;
    }

    /**
     * Gets group_homepage_url
     *
     * @return string
     */
    public function getGroupHomepageUrl()
    {
        return $this->container['group_homepage_url'];
    }

    /**
     * Sets group_homepage_url
     *
     * @param string $group_homepage_url group_homepage_url
     *
     * @return self
     */
    public function setGroupHomepageUrl($group_homepage_url)
    {
        if (is_null($group_homepage_url)) {
            array_push($this->openAPINullablesSetToNull, 'group_homepage_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('group_homepage_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['group_homepage_url'] = $group_homepage_url;

        return $this;
    }

    /**
     * Gets group_status_id
     *
     * @return int
     */
    public function getGroupStatusId()
    {
        return $this->container['group_status_id'];
    }

    /**
     * Sets group_status_id
     *
     * @param int $group_status_id group_status_id
     *
     * @return self
     */
    public function setGroupStatusId($group_status_id)
    {
        if (is_null($group_status_id)) {
            array_push($this->openAPINullablesSetToNull, 'group_status_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('group_status_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['group_status_id'] = $group_status_id;

        return $this;
    }

    /**
     * Gets group_type_id
     *
     * @return int
     */
    public function getGroupTypeId()
    {
        return $this->container['group_type_id'];
    }

    /**
     * Sets group_type_id
     *
     * @param int $group_type_id group_type_id
     *
     * @return self
     */
    public function setGroupTypeId($group_type_id)
    {
        if (is_null($group_type_id)) {
            array_push($this->openAPINullablesSetToNull, 'group_type_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('group_type_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['group_type_id'] = $group_type_id;

        return $this;
    }

    /**
     * Gets image_url
     *
     * @return string
     */
    public function getImageUrl()
    {
        return $this->container['image_url'];
    }

    /**
     * Sets image_url
     *
     * @param string $image_url image_url
     *
     * @return self
     */
    public function setImageUrl($image_url)
    {
        if (is_null($image_url)) {
            array_push($this->openAPINullablesSetToNull, 'image_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('image_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['image_url'] = $image_url;

        return $this;
    }

    /**
     * Gets max_members
     *
     * @return int
     * @deprecated
     */
    public function getMaxMembers()
    {
        return $this->container['max_members'];
    }

    /**
     * Sets max_members
     *
     * @param int $max_members Allowed maximal members
     *
     * @return self
     * @deprecated
     */
    public function setMaxMembers($max_members)
    {
        if (is_null($max_members)) {
            array_push($this->openAPINullablesSetToNull, 'max_members');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('max_members', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['max_members'] = $max_members;

        return $this;
    }

    /**
     * Gets meeting_time
     *
     * @return string
     */
    public function getMeetingTime()
    {
        return $this->container['meeting_time'];
    }

    /**
     * Sets meeting_time
     *
     * @param string $meeting_time meeting_time
     *
     * @return self
     */
    public function setMeetingTime($meeting_time)
    {
        if (is_null($meeting_time)) {
            array_push($this->openAPINullablesSetToNull, 'meeting_time');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('meeting_time', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['meeting_time'] = $meeting_time;

        return $this;
    }

    /**
     * Gets note
     *
     * @return string
     */
    public function getNote()
    {
        return $this->container['note'];
    }

    /**
     * Sets note
     *
     * @param string $note note
     *
     * @return self
     */
    public function setNote($note)
    {
        if (is_null($note)) {
            array_push($this->openAPINullablesSetToNull, 'note');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('note', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['note'] = $note;

        return $this;
    }

    /**
     * Gets sign_up_override_role_id
     *
     * @return int
     */
    public function getSignUpOverrideRoleId()
    {
        return $this->container['sign_up_override_role_id'];
    }

    /**
     * Sets sign_up_override_role_id
     *
     * @param int $sign_up_override_role_id sign_up_override_role_id
     *
     * @return self
     */
    public function setSignUpOverrideRoleId($sign_up_override_role_id)
    {
        if (is_null($sign_up_override_role_id)) {
            array_push($this->openAPINullablesSetToNull, 'sign_up_override_role_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('sign_up_override_role_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['sign_up_override_role_id'] = $sign_up_override_role_id;

        return $this;
    }

    /**
     * Gets target_group_id
     *
     * @return int
     */
    public function getTargetGroupId()
    {
        return $this->container['target_group_id'];
    }

    /**
     * Sets target_group_id
     *
     * @param int $target_group_id target_group_id
     *
     * @return self
     */
    public function setTargetGroupId($target_group_id)
    {
        if (is_null($target_group_id)) {
            array_push($this->openAPINullablesSetToNull, 'target_group_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('target_group_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['target_group_id'] = $target_group_id;

        return $this;
    }

    /**
     * Gets weekday
     *
     * @return int
     */
    public function getWeekday()
    {
        return $this->container['weekday'];
    }

    /**
     * Sets weekday
     *
     * @param int $weekday The number of the weekday. Starting with 0 = Sunday, 1 = Monday, ...
     *
     * @return self
     */
    public function setWeekday($weekday)
    {
        if (is_null($weekday)) {
            array_push($this->openAPINullablesSetToNull, 'weekday');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('weekday', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['weekday'] = $weekday;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


