<?php
/**
 * GetGroupsGroupIdMemberfields200ResponseDataInnerOneOf1Field
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ChurchTools
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ChurchTools REST API
 *
 * The ChurchTools REST API is the best entry point for developers to access ChurchTools. <br><br> **Authentication:** You need to be authorized to use some endpoints. Those endpoints are marked by a gray lock symbol. If you view the documentation, while you are logged into ChurchTools, all requests are already authorized. If you want to authorized a request, you need to provide a `Login Token` as `Authorization` header in the format `Authorization: Login <token>` or send a valid cookie. You can use the green \"Authorize\" dialog to enter those details and see how a request would look like in detail. <br><br> **Missing Endpoints:** Not all features are yet available by our new REST API. This documentation will grow in the future. We are working hard to add new endpoints with every ChurchTools version. The documentation will always show only those endpoints you can use with your ChurchTools installation.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@churchtools.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ChurchTools\Model;

use \ArrayAccess;
use \ChurchTools\ObjectSerializer;

/**
 * GetGroupsGroupIdMemberfields200ResponseDataInnerOneOf1Field Class Doc Comment
 *
 * @category Class
 * @package  ChurchTools
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetGroupsGroupIdMemberfields200ResponseDataInnerOneOf1Field implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'get_groups_groupId_memberfields_200_response_data_inner_oneOf_1_field';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'default_value' => 'string',
        'field_name' => 'string',
        'field_type_code' => 'string',
        'field_type_id' => 'int',
        'max_length' => 'int',
        'name' => 'string',
        'name_in_signup_form' => 'string',
        'note' => 'string',
        'note_in_signup_form' => 'string',
        'options' => '\ChurchTools\Model\GroupMemberField1OptionsInner[]',
        'reference_name' => 'string',
        'required_in_registration_form' => 'bool',
        'security_level' => 'int',
        'sort_key' => 'int',
        'use_in_registration_form' => 'bool',
        'group_id' => 'int',
        'id' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'default_value' => null,
        'field_name' => null,
        'field_type_code' => null,
        'field_type_id' => null,
        'max_length' => null,
        'name' => null,
        'name_in_signup_form' => null,
        'note' => null,
        'note_in_signup_form' => null,
        'options' => null,
        'reference_name' => null,
        'required_in_registration_form' => null,
        'security_level' => null,
        'sort_key' => null,
        'use_in_registration_form' => null,
        'group_id' => null,
        'id' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'default_value' => true,
        'field_name' => false,
        'field_type_code' => false,
        'field_type_id' => true,
        'max_length' => true,
        'name' => true,
        'name_in_signup_form' => true,
        'note' => true,
        'note_in_signup_form' => true,
        'options' => false,
        'reference_name' => true,
        'required_in_registration_form' => false,
        'security_level' => true,
        'sort_key' => true,
        'use_in_registration_form' => false,
        'group_id' => false,
        'id' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'default_value' => 'defaultValue',
        'field_name' => 'fieldName',
        'field_type_code' => 'fieldTypeCode',
        'field_type_id' => 'fieldTypeId',
        'max_length' => 'maxLength',
        'name' => 'name',
        'name_in_signup_form' => 'nameInSignupForm',
        'note' => 'note',
        'note_in_signup_form' => 'noteInSignupForm',
        'options' => 'options',
        'reference_name' => 'referenceName',
        'required_in_registration_form' => 'requiredInRegistrationForm',
        'security_level' => 'securityLevel',
        'sort_key' => 'sortKey',
        'use_in_registration_form' => 'useInRegistrationForm',
        'group_id' => 'groupId',
        'id' => 'id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'default_value' => 'setDefaultValue',
        'field_name' => 'setFieldName',
        'field_type_code' => 'setFieldTypeCode',
        'field_type_id' => 'setFieldTypeId',
        'max_length' => 'setMaxLength',
        'name' => 'setName',
        'name_in_signup_form' => 'setNameInSignupForm',
        'note' => 'setNote',
        'note_in_signup_form' => 'setNoteInSignupForm',
        'options' => 'setOptions',
        'reference_name' => 'setReferenceName',
        'required_in_registration_form' => 'setRequiredInRegistrationForm',
        'security_level' => 'setSecurityLevel',
        'sort_key' => 'setSortKey',
        'use_in_registration_form' => 'setUseInRegistrationForm',
        'group_id' => 'setGroupId',
        'id' => 'setId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'default_value' => 'getDefaultValue',
        'field_name' => 'getFieldName',
        'field_type_code' => 'getFieldTypeCode',
        'field_type_id' => 'getFieldTypeId',
        'max_length' => 'getMaxLength',
        'name' => 'getName',
        'name_in_signup_form' => 'getNameInSignupForm',
        'note' => 'getNote',
        'note_in_signup_form' => 'getNoteInSignupForm',
        'options' => 'getOptions',
        'reference_name' => 'getReferenceName',
        'required_in_registration_form' => 'getRequiredInRegistrationForm',
        'security_level' => 'getSecurityLevel',
        'sort_key' => 'getSortKey',
        'use_in_registration_form' => 'getUseInRegistrationForm',
        'group_id' => 'getGroupId',
        'id' => 'getId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const FIELD_TYPE_CODE_SELECT = 'select';
    public const FIELD_TYPE_CODE_TEXT = 'text';
    public const FIELD_TYPE_CODE_DATE = 'date';
    public const FIELD_TYPE_CODE_DATETIME = 'datetime';
    public const FIELD_TYPE_CODE_TEXTAREA = 'textarea';
    public const FIELD_TYPE_CODE_CHECKBOX = 'checkbox';
    public const FIELD_TYPE_CODE_NUMBER = 'number';
    public const FIELD_TYPE_CODE_MULTISELECT = 'multiselect';
    public const FIELD_TYPE_CODE_API = 'api';
    public const FIELD_TYPE_CODE_RADIOSELECT = 'radioselect';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFieldTypeCodeAllowableValues()
    {
        return [
            self::FIELD_TYPE_CODE_SELECT,
            self::FIELD_TYPE_CODE_TEXT,
            self::FIELD_TYPE_CODE_DATE,
            self::FIELD_TYPE_CODE_DATETIME,
            self::FIELD_TYPE_CODE_TEXTAREA,
            self::FIELD_TYPE_CODE_CHECKBOX,
            self::FIELD_TYPE_CODE_NUMBER,
            self::FIELD_TYPE_CODE_MULTISELECT,
            self::FIELD_TYPE_CODE_API,
            self::FIELD_TYPE_CODE_RADIOSELECT,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('default_value', $data ?? [], null);
        $this->setIfExists('field_name', $data ?? [], null);
        $this->setIfExists('field_type_code', $data ?? [], null);
        $this->setIfExists('field_type_id', $data ?? [], null);
        $this->setIfExists('max_length', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('name_in_signup_form', $data ?? [], null);
        $this->setIfExists('note', $data ?? [], null);
        $this->setIfExists('note_in_signup_form', $data ?? [], null);
        $this->setIfExists('options', $data ?? [], null);
        $this->setIfExists('reference_name', $data ?? [], null);
        $this->setIfExists('required_in_registration_form', $data ?? [], null);
        $this->setIfExists('security_level', $data ?? [], null);
        $this->setIfExists('sort_key', $data ?? [], null);
        $this->setIfExists('use_in_registration_form', $data ?? [], null);
        $this->setIfExists('group_id', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['default_value'] === null) {
            $invalidProperties[] = "'default_value' can't be null";
        }
        if ($this->container['field_name'] === null) {
            $invalidProperties[] = "'field_name' can't be null";
        }
        if ($this->container['field_type_code'] === null) {
            $invalidProperties[] = "'field_type_code' can't be null";
        }
        $allowedValues = $this->getFieldTypeCodeAllowableValues();
        if (!is_null($this->container['field_type_code']) && !in_array($this->container['field_type_code'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'field_type_code', must be one of '%s'",
                $this->container['field_type_code'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['field_type_id'] === null) {
            $invalidProperties[] = "'field_type_id' can't be null";
        }
        if ($this->container['max_length'] === null) {
            $invalidProperties[] = "'max_length' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['name_in_signup_form'] === null) {
            $invalidProperties[] = "'name_in_signup_form' can't be null";
        }
        if ($this->container['note'] === null) {
            $invalidProperties[] = "'note' can't be null";
        }
        if ($this->container['note_in_signup_form'] === null) {
            $invalidProperties[] = "'note_in_signup_form' can't be null";
        }
        if ($this->container['options'] === null) {
            $invalidProperties[] = "'options' can't be null";
        }
        if ($this->container['reference_name'] === null) {
            $invalidProperties[] = "'reference_name' can't be null";
        }
        if ($this->container['required_in_registration_form'] === null) {
            $invalidProperties[] = "'required_in_registration_form' can't be null";
        }
        if ($this->container['security_level'] === null) {
            $invalidProperties[] = "'security_level' can't be null";
        }
        if ($this->container['sort_key'] === null) {
            $invalidProperties[] = "'sort_key' can't be null";
        }
        if ($this->container['use_in_registration_form'] === null) {
            $invalidProperties[] = "'use_in_registration_form' can't be null";
        }
        if ($this->container['group_id'] === null) {
            $invalidProperties[] = "'group_id' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets default_value
     *
     * @return string
     */
    public function getDefaultValue()
    {
        return $this->container['default_value'];
    }

    /**
     * Sets default_value
     *
     * @param string $default_value default_value
     *
     * @return self
     */
    public function setDefaultValue($default_value)
    {
        if (is_null($default_value)) {
            array_push($this->openAPINullablesSetToNull, 'default_value');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('default_value', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['default_value'] = $default_value;

        return $this;
    }

    /**
     * Gets field_name
     *
     * @return string
     * @deprecated
     */
    public function getFieldName()
    {
        return $this->container['field_name'];
    }

    /**
     * Sets field_name
     *
     * @param string $field_name field_name
     *
     * @return self
     * @deprecated
     */
    public function setFieldName($field_name)
    {
        if (is_null($field_name)) {
            throw new \InvalidArgumentException('non-nullable field_name cannot be null');
        }
        $this->container['field_name'] = $field_name;

        return $this;
    }

    /**
     * Gets field_type_code
     *
     * @return string
     */
    public function getFieldTypeCode()
    {
        return $this->container['field_type_code'];
    }

    /**
     * Sets field_type_code
     *
     * @param string $field_type_code The intern code of the field type the field belongs to. This is used to define the type of the field.
     *
     * @return self
     */
    public function setFieldTypeCode($field_type_code)
    {
        if (is_null($field_type_code)) {
            throw new \InvalidArgumentException('non-nullable field_type_code cannot be null');
        }
        $allowedValues = $this->getFieldTypeCodeAllowableValues();
        if (!in_array($field_type_code, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'field_type_code', must be one of '%s'",
                    $field_type_code,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['field_type_code'] = $field_type_code;

        return $this;
    }

    /**
     * Gets field_type_id
     *
     * @return int
     */
    public function getFieldTypeId()
    {
        return $this->container['field_type_id'];
    }

    /**
     * Sets field_type_id
     *
     * @param int $field_type_id field_type_id
     *
     * @return self
     */
    public function setFieldTypeId($field_type_id)
    {
        if (is_null($field_type_id)) {
            array_push($this->openAPINullablesSetToNull, 'field_type_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('field_type_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['field_type_id'] = $field_type_id;

        return $this;
    }

    /**
     * Gets max_length
     *
     * @return int
     */
    public function getMaxLength()
    {
        return $this->container['max_length'];
    }

    /**
     * Sets max_length
     *
     * @param int $max_length max_length
     *
     * @return self
     */
    public function setMaxLength($max_length)
    {
        if (is_null($max_length)) {
            array_push($this->openAPINullablesSetToNull, 'max_length');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('max_length', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['max_length'] = $max_length;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            array_push($this->openAPINullablesSetToNull, 'name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets name_in_signup_form
     *
     * @return string
     */
    public function getNameInSignupForm()
    {
        return $this->container['name_in_signup_form'];
    }

    /**
     * Sets name_in_signup_form
     *
     * @param string $name_in_signup_form name_in_signup_form
     *
     * @return self
     */
    public function setNameInSignupForm($name_in_signup_form)
    {
        if (is_null($name_in_signup_form)) {
            array_push($this->openAPINullablesSetToNull, 'name_in_signup_form');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name_in_signup_form', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['name_in_signup_form'] = $name_in_signup_form;

        return $this;
    }

    /**
     * Gets note
     *
     * @return string
     */
    public function getNote()
    {
        return $this->container['note'];
    }

    /**
     * Sets note
     *
     * @param string $note note
     *
     * @return self
     */
    public function setNote($note)
    {
        if (is_null($note)) {
            array_push($this->openAPINullablesSetToNull, 'note');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('note', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['note'] = $note;

        return $this;
    }

    /**
     * Gets note_in_signup_form
     *
     * @return string
     */
    public function getNoteInSignupForm()
    {
        return $this->container['note_in_signup_form'];
    }

    /**
     * Sets note_in_signup_form
     *
     * @param string $note_in_signup_form note_in_signup_form
     *
     * @return self
     */
    public function setNoteInSignupForm($note_in_signup_form)
    {
        if (is_null($note_in_signup_form)) {
            array_push($this->openAPINullablesSetToNull, 'note_in_signup_form');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('note_in_signup_form', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['note_in_signup_form'] = $note_in_signup_form;

        return $this;
    }

    /**
     * Gets options
     *
     * @return \ChurchTools\Model\GroupMemberField1OptionsInner[]
     */
    public function getOptions()
    {
        return $this->container['options'];
    }

    /**
     * Sets options
     *
     * @param \ChurchTools\Model\GroupMemberField1OptionsInner[] $options options
     *
     * @return self
     */
    public function setOptions($options)
    {
        if (is_null($options)) {
            throw new \InvalidArgumentException('non-nullable options cannot be null');
        }
        $this->container['options'] = $options;

        return $this;
    }

    /**
     * Gets reference_name
     *
     * @return string
     */
    public function getReferenceName()
    {
        return $this->container['reference_name'];
    }

    /**
     * Sets reference_name
     *
     * @param string $reference_name reference_name
     *
     * @return self
     */
    public function setReferenceName($reference_name)
    {
        if (is_null($reference_name)) {
            array_push($this->openAPINullablesSetToNull, 'reference_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('reference_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['reference_name'] = $reference_name;

        return $this;
    }

    /**
     * Gets required_in_registration_form
     *
     * @return bool
     */
    public function getRequiredInRegistrationForm()
    {
        return $this->container['required_in_registration_form'];
    }

    /**
     * Sets required_in_registration_form
     *
     * @param bool $required_in_registration_form required_in_registration_form
     *
     * @return self
     */
    public function setRequiredInRegistrationForm($required_in_registration_form)
    {
        if (is_null($required_in_registration_form)) {
            throw new \InvalidArgumentException('non-nullable required_in_registration_form cannot be null');
        }
        $this->container['required_in_registration_form'] = $required_in_registration_form;

        return $this;
    }

    /**
     * Gets security_level
     *
     * @return int
     */
    public function getSecurityLevel()
    {
        return $this->container['security_level'];
    }

    /**
     * Sets security_level
     *
     * @param int $security_level security_level
     *
     * @return self
     */
    public function setSecurityLevel($security_level)
    {
        if (is_null($security_level)) {
            array_push($this->openAPINullablesSetToNull, 'security_level');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('security_level', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['security_level'] = $security_level;

        return $this;
    }

    /**
     * Gets sort_key
     *
     * @return int
     */
    public function getSortKey()
    {
        return $this->container['sort_key'];
    }

    /**
     * Sets sort_key
     *
     * @param int $sort_key sort_key
     *
     * @return self
     */
    public function setSortKey($sort_key)
    {
        if (is_null($sort_key)) {
            array_push($this->openAPINullablesSetToNull, 'sort_key');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('sort_key', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['sort_key'] = $sort_key;

        return $this;
    }

    /**
     * Gets use_in_registration_form
     *
     * @return bool
     */
    public function getUseInRegistrationForm()
    {
        return $this->container['use_in_registration_form'];
    }

    /**
     * Sets use_in_registration_form
     *
     * @param bool $use_in_registration_form use_in_registration_form
     *
     * @return self
     */
    public function setUseInRegistrationForm($use_in_registration_form)
    {
        if (is_null($use_in_registration_form)) {
            throw new \InvalidArgumentException('non-nullable use_in_registration_form cannot be null');
        }
        $this->container['use_in_registration_form'] = $use_in_registration_form;

        return $this;
    }

    /**
     * Gets group_id
     *
     * @return int
     */
    public function getGroupId()
    {
        return $this->container['group_id'];
    }

    /**
     * Sets group_id
     *
     * @param int $group_id group_id
     *
     * @return self
     */
    public function setGroupId($group_id)
    {
        if (is_null($group_id)) {
            throw new \InvalidArgumentException('non-nullable group_id cannot be null');
        }
        $this->container['group_id'] = $group_id;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


