<?php
/**
 * GetPermissionsInternalGroups200ResponseDataChurchdb
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ChurchTools
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ChurchTools REST API
 *
 * The ChurchTools REST API is the best entry point for developers to access ChurchTools. <br><br> **Authentication:** You need to be authorized to use some endpoints. Those endpoints are marked by a gray lock symbol. If you view the documentation, while you are logged into ChurchTools, all requests are already authorized. If you want to authorized a request, you need to provide a `Login Token` as `Authorization` header in the format `Authorization: Login <token>` or send a valid cookie. You can use the green \"Authorize\" dialog to enter those details and see how a request would look like in detail. <br><br> **Missing Endpoints:** Not all features are yet available by our new REST API. This documentation will grow in the future. We are working hard to add new endpoints with every ChurchTools version. The documentation will always show only those endpoints you can use with your ChurchTools installation.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@churchtools.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ChurchTools\Model;

use \ArrayAccess;
use \ChurchTools\ObjectSerializer;

/**
 * GetPermissionsInternalGroups200ResponseDataChurchdb Class Doc Comment
 *
 * @category Class
 * @description Group Internal Permission, which Affect a Person
 * @package  ChurchTools
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetPermissionsInternalGroups200ResponseDataChurchdb implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'get_permissions_internal_groups_200_response_data_churchdb';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'add_person' => 'bool',
        'admin_automatic_emails' => 'bool',
        'admin_followup' => 'bool',
        'admin_group_chat' => 'bool',
        'admin_group_fields' => 'bool',
        'admin_group_member_fields' => 'bool',
        'admin_meetings' => 'bool',
        'admin_posts' => 'bool',
        'admin_routines' => 'bool',
        'create_group' => 'bool',
        'create_notes' => 'bool',
        'create_post_group_intern' => 'bool',
        'create_post_group_visible' => 'bool',
        'do_followup' => 'bool',
        'do_group_meeting' => 'bool',
        'edit_basic_group_memberships' => 'bool',
        'edit_group_basic_settings' => 'bool',
        'edit_group_hierarchy' => 'bool',
        'edit_group_infos' => 'bool',
        'edit_group_member_fields' => 'float',
        'edit_group_memberships' => 'bool',
        'edit_own_group_member_fields' => 'float',
        'edit_own_groupmemberfields' => 'bool',
        'edit_person_fields_of_group_members' => 'float',
        'edit_persons' => 'bool',
        'export_group_members' => 'bool',
        'get_emails' => 'bool',
        'invite_person' => 'bool',
        'mail_group_members' => 'bool',
        'remove_from_group' => 'bool',
        'see_group' => 'float',
        'see_group_member_fields' => 'float',
        'see_group_tags' => 'bool',
        'see_groupmemberfields' => 'float',
        'see_hidden_group' => 'bool',
        'see_own_group_member_fields' => 'float',
        'see_persons' => 'float',
        'see_tags' => 'bool',
        'view_history' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'add_person' => null,
        'admin_automatic_emails' => null,
        'admin_followup' => null,
        'admin_group_chat' => null,
        'admin_group_fields' => null,
        'admin_group_member_fields' => null,
        'admin_meetings' => null,
        'admin_posts' => null,
        'admin_routines' => null,
        'create_group' => null,
        'create_notes' => null,
        'create_post_group_intern' => null,
        'create_post_group_visible' => null,
        'do_followup' => null,
        'do_group_meeting' => null,
        'edit_basic_group_memberships' => null,
        'edit_group_basic_settings' => null,
        'edit_group_hierarchy' => null,
        'edit_group_infos' => null,
        'edit_group_member_fields' => null,
        'edit_group_memberships' => null,
        'edit_own_group_member_fields' => null,
        'edit_own_groupmemberfields' => null,
        'edit_person_fields_of_group_members' => null,
        'edit_persons' => null,
        'export_group_members' => null,
        'get_emails' => null,
        'invite_person' => null,
        'mail_group_members' => null,
        'remove_from_group' => null,
        'see_group' => null,
        'see_group_member_fields' => null,
        'see_group_tags' => null,
        'see_groupmemberfields' => null,
        'see_hidden_group' => null,
        'see_own_group_member_fields' => null,
        'see_persons' => null,
        'see_tags' => null,
        'view_history' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'add_person' => false,
        'admin_automatic_emails' => false,
        'admin_followup' => false,
        'admin_group_chat' => false,
        'admin_group_fields' => false,
        'admin_group_member_fields' => false,
        'admin_meetings' => false,
        'admin_posts' => false,
        'admin_routines' => false,
        'create_group' => false,
        'create_notes' => false,
        'create_post_group_intern' => false,
        'create_post_group_visible' => false,
        'do_followup' => false,
        'do_group_meeting' => false,
        'edit_basic_group_memberships' => false,
        'edit_group_basic_settings' => false,
        'edit_group_hierarchy' => false,
        'edit_group_infos' => false,
        'edit_group_member_fields' => false,
        'edit_group_memberships' => false,
        'edit_own_group_member_fields' => false,
        'edit_own_groupmemberfields' => false,
        'edit_person_fields_of_group_members' => false,
        'edit_persons' => false,
        'export_group_members' => false,
        'get_emails' => false,
        'invite_person' => false,
        'mail_group_members' => false,
        'remove_from_group' => false,
        'see_group' => false,
        'see_group_member_fields' => false,
        'see_group_tags' => false,
        'see_groupmemberfields' => false,
        'see_hidden_group' => false,
        'see_own_group_member_fields' => false,
        'see_persons' => false,
        'see_tags' => false,
        'view_history' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'add_person' => '+add person',
        'admin_automatic_emails' => '+admin automatic emails',
        'admin_followup' => '+admin followup',
        'admin_group_chat' => '+admin group chat',
        'admin_group_fields' => '+admin group fields',
        'admin_group_member_fields' => '+admin group member fields',
        'admin_meetings' => '+admin meetings',
        'admin_posts' => '+admin posts',
        'admin_routines' => '+admin routines',
        'create_group' => '+create group',
        'create_notes' => '+create notes',
        'create_post_group_intern' => '+create post group intern',
        'create_post_group_visible' => '+create post group visible',
        'do_followup' => '+do followup',
        'do_group_meeting' => '+do group meeting',
        'edit_basic_group_memberships' => '+edit basic group memberships',
        'edit_group_basic_settings' => '+edit group basic settings',
        'edit_group_hierarchy' => '+edit group hierarchy',
        'edit_group_infos' => '+edit group infos',
        'edit_group_member_fields' => '+edit group member fields',
        'edit_group_memberships' => '+edit group memberships',
        'edit_own_group_member_fields' => '+edit own group member fields',
        'edit_own_groupmemberfields' => '+edit own groupmemberfields',
        'edit_person_fields_of_group_members' => '+edit person fields of group members',
        'edit_persons' => '+edit persons',
        'export_group_members' => '+export group members',
        'get_emails' => '+get emails',
        'invite_person' => '+invite person',
        'mail_group_members' => '+mail group members',
        'remove_from_group' => '+remove from group',
        'see_group' => '+see group',
        'see_group_member_fields' => '+see group member fields',
        'see_group_tags' => '+see group tags',
        'see_groupmemberfields' => '+see groupmemberfields',
        'see_hidden_group' => '+see hidden group',
        'see_own_group_member_fields' => '+see own group member fields',
        'see_persons' => '+see persons',
        'see_tags' => '+see tags',
        'view_history' => '+view history'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'add_person' => 'setAddPerson',
        'admin_automatic_emails' => 'setAdminAutomaticEmails',
        'admin_followup' => 'setAdminFollowup',
        'admin_group_chat' => 'setAdminGroupChat',
        'admin_group_fields' => 'setAdminGroupFields',
        'admin_group_member_fields' => 'setAdminGroupMemberFields',
        'admin_meetings' => 'setAdminMeetings',
        'admin_posts' => 'setAdminPosts',
        'admin_routines' => 'setAdminRoutines',
        'create_group' => 'setCreateGroup',
        'create_notes' => 'setCreateNotes',
        'create_post_group_intern' => 'setCreatePostGroupIntern',
        'create_post_group_visible' => 'setCreatePostGroupVisible',
        'do_followup' => 'setDoFollowup',
        'do_group_meeting' => 'setDoGroupMeeting',
        'edit_basic_group_memberships' => 'setEditBasicGroupMemberships',
        'edit_group_basic_settings' => 'setEditGroupBasicSettings',
        'edit_group_hierarchy' => 'setEditGroupHierarchy',
        'edit_group_infos' => 'setEditGroupInfos',
        'edit_group_member_fields' => 'setEditGroupMemberFields',
        'edit_group_memberships' => 'setEditGroupMemberships',
        'edit_own_group_member_fields' => 'setEditOwnGroupMemberFields',
        'edit_own_groupmemberfields' => 'setEditOwnGroupmemberfields',
        'edit_person_fields_of_group_members' => 'setEditPersonFieldsOfGroupMembers',
        'edit_persons' => 'setEditPersons',
        'export_group_members' => 'setExportGroupMembers',
        'get_emails' => 'setGetEmails',
        'invite_person' => 'setInvitePerson',
        'mail_group_members' => 'setMailGroupMembers',
        'remove_from_group' => 'setRemoveFromGroup',
        'see_group' => 'setSeeGroup',
        'see_group_member_fields' => 'setSeeGroupMemberFields',
        'see_group_tags' => 'setSeeGroupTags',
        'see_groupmemberfields' => 'setSeeGroupmemberfields',
        'see_hidden_group' => 'setSeeHiddenGroup',
        'see_own_group_member_fields' => 'setSeeOwnGroupMemberFields',
        'see_persons' => 'setSeePersons',
        'see_tags' => 'setSeeTags',
        'view_history' => 'setViewHistory'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'add_person' => 'getAddPerson',
        'admin_automatic_emails' => 'getAdminAutomaticEmails',
        'admin_followup' => 'getAdminFollowup',
        'admin_group_chat' => 'getAdminGroupChat',
        'admin_group_fields' => 'getAdminGroupFields',
        'admin_group_member_fields' => 'getAdminGroupMemberFields',
        'admin_meetings' => 'getAdminMeetings',
        'admin_posts' => 'getAdminPosts',
        'admin_routines' => 'getAdminRoutines',
        'create_group' => 'getCreateGroup',
        'create_notes' => 'getCreateNotes',
        'create_post_group_intern' => 'getCreatePostGroupIntern',
        'create_post_group_visible' => 'getCreatePostGroupVisible',
        'do_followup' => 'getDoFollowup',
        'do_group_meeting' => 'getDoGroupMeeting',
        'edit_basic_group_memberships' => 'getEditBasicGroupMemberships',
        'edit_group_basic_settings' => 'getEditGroupBasicSettings',
        'edit_group_hierarchy' => 'getEditGroupHierarchy',
        'edit_group_infos' => 'getEditGroupInfos',
        'edit_group_member_fields' => 'getEditGroupMemberFields',
        'edit_group_memberships' => 'getEditGroupMemberships',
        'edit_own_group_member_fields' => 'getEditOwnGroupMemberFields',
        'edit_own_groupmemberfields' => 'getEditOwnGroupmemberfields',
        'edit_person_fields_of_group_members' => 'getEditPersonFieldsOfGroupMembers',
        'edit_persons' => 'getEditPersons',
        'export_group_members' => 'getExportGroupMembers',
        'get_emails' => 'getGetEmails',
        'invite_person' => 'getInvitePerson',
        'mail_group_members' => 'getMailGroupMembers',
        'remove_from_group' => 'getRemoveFromGroup',
        'see_group' => 'getSeeGroup',
        'see_group_member_fields' => 'getSeeGroupMemberFields',
        'see_group_tags' => 'getSeeGroupTags',
        'see_groupmemberfields' => 'getSeeGroupmemberfields',
        'see_hidden_group' => 'getSeeHiddenGroup',
        'see_own_group_member_fields' => 'getSeeOwnGroupMemberFields',
        'see_persons' => 'getSeePersons',
        'see_tags' => 'getSeeTags',
        'view_history' => 'getViewHistory'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('add_person', $data ?? [], null);
        $this->setIfExists('admin_automatic_emails', $data ?? [], null);
        $this->setIfExists('admin_followup', $data ?? [], null);
        $this->setIfExists('admin_group_chat', $data ?? [], null);
        $this->setIfExists('admin_group_fields', $data ?? [], null);
        $this->setIfExists('admin_group_member_fields', $data ?? [], null);
        $this->setIfExists('admin_meetings', $data ?? [], null);
        $this->setIfExists('admin_posts', $data ?? [], null);
        $this->setIfExists('admin_routines', $data ?? [], null);
        $this->setIfExists('create_group', $data ?? [], null);
        $this->setIfExists('create_notes', $data ?? [], null);
        $this->setIfExists('create_post_group_intern', $data ?? [], null);
        $this->setIfExists('create_post_group_visible', $data ?? [], null);
        $this->setIfExists('do_followup', $data ?? [], null);
        $this->setIfExists('do_group_meeting', $data ?? [], null);
        $this->setIfExists('edit_basic_group_memberships', $data ?? [], null);
        $this->setIfExists('edit_group_basic_settings', $data ?? [], null);
        $this->setIfExists('edit_group_hierarchy', $data ?? [], null);
        $this->setIfExists('edit_group_infos', $data ?? [], null);
        $this->setIfExists('edit_group_member_fields', $data ?? [], null);
        $this->setIfExists('edit_group_memberships', $data ?? [], null);
        $this->setIfExists('edit_own_group_member_fields', $data ?? [], null);
        $this->setIfExists('edit_own_groupmemberfields', $data ?? [], null);
        $this->setIfExists('edit_person_fields_of_group_members', $data ?? [], null);
        $this->setIfExists('edit_persons', $data ?? [], null);
        $this->setIfExists('export_group_members', $data ?? [], null);
        $this->setIfExists('get_emails', $data ?? [], null);
        $this->setIfExists('invite_person', $data ?? [], null);
        $this->setIfExists('mail_group_members', $data ?? [], null);
        $this->setIfExists('remove_from_group', $data ?? [], null);
        $this->setIfExists('see_group', $data ?? [], null);
        $this->setIfExists('see_group_member_fields', $data ?? [], null);
        $this->setIfExists('see_group_tags', $data ?? [], null);
        $this->setIfExists('see_groupmemberfields', $data ?? [], null);
        $this->setIfExists('see_hidden_group', $data ?? [], null);
        $this->setIfExists('see_own_group_member_fields', $data ?? [], null);
        $this->setIfExists('see_persons', $data ?? [], null);
        $this->setIfExists('see_tags', $data ?? [], null);
        $this->setIfExists('view_history', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets add_person
     *
     * @return bool|null
     */
    public function getAddPerson()
    {
        return $this->container['add_person'];
    }

    /**
     * Sets add_person
     *
     * @param bool|null $add_person add_person
     *
     * @return self
     */
    public function setAddPerson($add_person)
    {
        if (is_null($add_person)) {
            throw new \InvalidArgumentException('non-nullable add_person cannot be null');
        }
        $this->container['add_person'] = $add_person;

        return $this;
    }

    /**
     * Gets admin_automatic_emails
     *
     * @return bool|null
     */
    public function getAdminAutomaticEmails()
    {
        return $this->container['admin_automatic_emails'];
    }

    /**
     * Sets admin_automatic_emails
     *
     * @param bool|null $admin_automatic_emails admin_automatic_emails
     *
     * @return self
     */
    public function setAdminAutomaticEmails($admin_automatic_emails)
    {
        if (is_null($admin_automatic_emails)) {
            throw new \InvalidArgumentException('non-nullable admin_automatic_emails cannot be null');
        }
        $this->container['admin_automatic_emails'] = $admin_automatic_emails;

        return $this;
    }

    /**
     * Gets admin_followup
     *
     * @return bool|null
     */
    public function getAdminFollowup()
    {
        return $this->container['admin_followup'];
    }

    /**
     * Sets admin_followup
     *
     * @param bool|null $admin_followup admin_followup
     *
     * @return self
     */
    public function setAdminFollowup($admin_followup)
    {
        if (is_null($admin_followup)) {
            throw new \InvalidArgumentException('non-nullable admin_followup cannot be null');
        }
        $this->container['admin_followup'] = $admin_followup;

        return $this;
    }

    /**
     * Gets admin_group_chat
     *
     * @return bool|null
     */
    public function getAdminGroupChat()
    {
        return $this->container['admin_group_chat'];
    }

    /**
     * Sets admin_group_chat
     *
     * @param bool|null $admin_group_chat admin_group_chat
     *
     * @return self
     */
    public function setAdminGroupChat($admin_group_chat)
    {
        if (is_null($admin_group_chat)) {
            throw new \InvalidArgumentException('non-nullable admin_group_chat cannot be null');
        }
        $this->container['admin_group_chat'] = $admin_group_chat;

        return $this;
    }

    /**
     * Gets admin_group_fields
     *
     * @return bool|null
     * @deprecated
     */
    public function getAdminGroupFields()
    {
        return $this->container['admin_group_fields'];
    }

    /**
     * Sets admin_group_fields
     *
     * @param bool|null $admin_group_fields admin_group_fields
     *
     * @return self
     * @deprecated
     */
    public function setAdminGroupFields($admin_group_fields)
    {
        if (is_null($admin_group_fields)) {
            throw new \InvalidArgumentException('non-nullable admin_group_fields cannot be null');
        }
        $this->container['admin_group_fields'] = $admin_group_fields;

        return $this;
    }

    /**
     * Gets admin_group_member_fields
     *
     * @return bool|null
     */
    public function getAdminGroupMemberFields()
    {
        return $this->container['admin_group_member_fields'];
    }

    /**
     * Sets admin_group_member_fields
     *
     * @param bool|null $admin_group_member_fields admin_group_member_fields
     *
     * @return self
     */
    public function setAdminGroupMemberFields($admin_group_member_fields)
    {
        if (is_null($admin_group_member_fields)) {
            throw new \InvalidArgumentException('non-nullable admin_group_member_fields cannot be null');
        }
        $this->container['admin_group_member_fields'] = $admin_group_member_fields;

        return $this;
    }

    /**
     * Gets admin_meetings
     *
     * @return bool|null
     */
    public function getAdminMeetings()
    {
        return $this->container['admin_meetings'];
    }

    /**
     * Sets admin_meetings
     *
     * @param bool|null $admin_meetings admin_meetings
     *
     * @return self
     */
    public function setAdminMeetings($admin_meetings)
    {
        if (is_null($admin_meetings)) {
            throw new \InvalidArgumentException('non-nullable admin_meetings cannot be null');
        }
        $this->container['admin_meetings'] = $admin_meetings;

        return $this;
    }

    /**
     * Gets admin_posts
     *
     * @return bool|null
     */
    public function getAdminPosts()
    {
        return $this->container['admin_posts'];
    }

    /**
     * Sets admin_posts
     *
     * @param bool|null $admin_posts admin_posts
     *
     * @return self
     */
    public function setAdminPosts($admin_posts)
    {
        if (is_null($admin_posts)) {
            throw new \InvalidArgumentException('non-nullable admin_posts cannot be null');
        }
        $this->container['admin_posts'] = $admin_posts;

        return $this;
    }

    /**
     * Gets admin_routines
     *
     * @return bool|null
     */
    public function getAdminRoutines()
    {
        return $this->container['admin_routines'];
    }

    /**
     * Sets admin_routines
     *
     * @param bool|null $admin_routines admin_routines
     *
     * @return self
     */
    public function setAdminRoutines($admin_routines)
    {
        if (is_null($admin_routines)) {
            throw new \InvalidArgumentException('non-nullable admin_routines cannot be null');
        }
        $this->container['admin_routines'] = $admin_routines;

        return $this;
    }

    /**
     * Gets create_group
     *
     * @return bool|null
     */
    public function getCreateGroup()
    {
        return $this->container['create_group'];
    }

    /**
     * Sets create_group
     *
     * @param bool|null $create_group create_group
     *
     * @return self
     */
    public function setCreateGroup($create_group)
    {
        if (is_null($create_group)) {
            throw new \InvalidArgumentException('non-nullable create_group cannot be null');
        }
        $this->container['create_group'] = $create_group;

        return $this;
    }

    /**
     * Gets create_notes
     *
     * @return bool|null
     */
    public function getCreateNotes()
    {
        return $this->container['create_notes'];
    }

    /**
     * Sets create_notes
     *
     * @param bool|null $create_notes create_notes
     *
     * @return self
     */
    public function setCreateNotes($create_notes)
    {
        if (is_null($create_notes)) {
            throw new \InvalidArgumentException('non-nullable create_notes cannot be null');
        }
        $this->container['create_notes'] = $create_notes;

        return $this;
    }

    /**
     * Gets create_post_group_intern
     *
     * @return bool|null
     */
    public function getCreatePostGroupIntern()
    {
        return $this->container['create_post_group_intern'];
    }

    /**
     * Sets create_post_group_intern
     *
     * @param bool|null $create_post_group_intern create_post_group_intern
     *
     * @return self
     */
    public function setCreatePostGroupIntern($create_post_group_intern)
    {
        if (is_null($create_post_group_intern)) {
            throw new \InvalidArgumentException('non-nullable create_post_group_intern cannot be null');
        }
        $this->container['create_post_group_intern'] = $create_post_group_intern;

        return $this;
    }

    /**
     * Gets create_post_group_visible
     *
     * @return bool|null
     */
    public function getCreatePostGroupVisible()
    {
        return $this->container['create_post_group_visible'];
    }

    /**
     * Sets create_post_group_visible
     *
     * @param bool|null $create_post_group_visible create_post_group_visible
     *
     * @return self
     */
    public function setCreatePostGroupVisible($create_post_group_visible)
    {
        if (is_null($create_post_group_visible)) {
            throw new \InvalidArgumentException('non-nullable create_post_group_visible cannot be null');
        }
        $this->container['create_post_group_visible'] = $create_post_group_visible;

        return $this;
    }

    /**
     * Gets do_followup
     *
     * @return bool|null
     */
    public function getDoFollowup()
    {
        return $this->container['do_followup'];
    }

    /**
     * Sets do_followup
     *
     * @param bool|null $do_followup do_followup
     *
     * @return self
     */
    public function setDoFollowup($do_followup)
    {
        if (is_null($do_followup)) {
            throw new \InvalidArgumentException('non-nullable do_followup cannot be null');
        }
        $this->container['do_followup'] = $do_followup;

        return $this;
    }

    /**
     * Gets do_group_meeting
     *
     * @return bool|null
     */
    public function getDoGroupMeeting()
    {
        return $this->container['do_group_meeting'];
    }

    /**
     * Sets do_group_meeting
     *
     * @param bool|null $do_group_meeting do_group_meeting
     *
     * @return self
     */
    public function setDoGroupMeeting($do_group_meeting)
    {
        if (is_null($do_group_meeting)) {
            throw new \InvalidArgumentException('non-nullable do_group_meeting cannot be null');
        }
        $this->container['do_group_meeting'] = $do_group_meeting;

        return $this;
    }

    /**
     * Gets edit_basic_group_memberships
     *
     * @return bool|null
     */
    public function getEditBasicGroupMemberships()
    {
        return $this->container['edit_basic_group_memberships'];
    }

    /**
     * Sets edit_basic_group_memberships
     *
     * @param bool|null $edit_basic_group_memberships edit_basic_group_memberships
     *
     * @return self
     */
    public function setEditBasicGroupMemberships($edit_basic_group_memberships)
    {
        if (is_null($edit_basic_group_memberships)) {
            throw new \InvalidArgumentException('non-nullable edit_basic_group_memberships cannot be null');
        }
        $this->container['edit_basic_group_memberships'] = $edit_basic_group_memberships;

        return $this;
    }

    /**
     * Gets edit_group_basic_settings
     *
     * @return bool|null
     */
    public function getEditGroupBasicSettings()
    {
        return $this->container['edit_group_basic_settings'];
    }

    /**
     * Sets edit_group_basic_settings
     *
     * @param bool|null $edit_group_basic_settings edit_group_basic_settings
     *
     * @return self
     */
    public function setEditGroupBasicSettings($edit_group_basic_settings)
    {
        if (is_null($edit_group_basic_settings)) {
            throw new \InvalidArgumentException('non-nullable edit_group_basic_settings cannot be null');
        }
        $this->container['edit_group_basic_settings'] = $edit_group_basic_settings;

        return $this;
    }

    /**
     * Gets edit_group_hierarchy
     *
     * @return bool|null
     */
    public function getEditGroupHierarchy()
    {
        return $this->container['edit_group_hierarchy'];
    }

    /**
     * Sets edit_group_hierarchy
     *
     * @param bool|null $edit_group_hierarchy edit_group_hierarchy
     *
     * @return self
     */
    public function setEditGroupHierarchy($edit_group_hierarchy)
    {
        if (is_null($edit_group_hierarchy)) {
            throw new \InvalidArgumentException('non-nullable edit_group_hierarchy cannot be null');
        }
        $this->container['edit_group_hierarchy'] = $edit_group_hierarchy;

        return $this;
    }

    /**
     * Gets edit_group_infos
     *
     * @return bool|null
     */
    public function getEditGroupInfos()
    {
        return $this->container['edit_group_infos'];
    }

    /**
     * Sets edit_group_infos
     *
     * @param bool|null $edit_group_infos edit_group_infos
     *
     * @return self
     */
    public function setEditGroupInfos($edit_group_infos)
    {
        if (is_null($edit_group_infos)) {
            throw new \InvalidArgumentException('non-nullable edit_group_infos cannot be null');
        }
        $this->container['edit_group_infos'] = $edit_group_infos;

        return $this;
    }

    /**
     * Gets edit_group_member_fields
     *
     * @return float|null
     */
    public function getEditGroupMemberFields()
    {
        return $this->container['edit_group_member_fields'];
    }

    /**
     * Sets edit_group_member_fields
     *
     * @param float|null $edit_group_member_fields edit_group_member_fields
     *
     * @return self
     */
    public function setEditGroupMemberFields($edit_group_member_fields)
    {
        if (is_null($edit_group_member_fields)) {
            throw new \InvalidArgumentException('non-nullable edit_group_member_fields cannot be null');
        }
        $this->container['edit_group_member_fields'] = $edit_group_member_fields;

        return $this;
    }

    /**
     * Gets edit_group_memberships
     *
     * @return bool|null
     * @deprecated
     */
    public function getEditGroupMemberships()
    {
        return $this->container['edit_group_memberships'];
    }

    /**
     * Sets edit_group_memberships
     *
     * @param bool|null $edit_group_memberships edit_group_memberships
     *
     * @return self
     * @deprecated
     */
    public function setEditGroupMemberships($edit_group_memberships)
    {
        if (is_null($edit_group_memberships)) {
            throw new \InvalidArgumentException('non-nullable edit_group_memberships cannot be null');
        }
        $this->container['edit_group_memberships'] = $edit_group_memberships;

        return $this;
    }

    /**
     * Gets edit_own_group_member_fields
     *
     * @return float|null
     */
    public function getEditOwnGroupMemberFields()
    {
        return $this->container['edit_own_group_member_fields'];
    }

    /**
     * Sets edit_own_group_member_fields
     *
     * @param float|null $edit_own_group_member_fields edit_own_group_member_fields
     *
     * @return self
     */
    public function setEditOwnGroupMemberFields($edit_own_group_member_fields)
    {
        if (is_null($edit_own_group_member_fields)) {
            throw new \InvalidArgumentException('non-nullable edit_own_group_member_fields cannot be null');
        }
        $this->container['edit_own_group_member_fields'] = $edit_own_group_member_fields;

        return $this;
    }

    /**
     * Gets edit_own_groupmemberfields
     *
     * @return bool|null
     * @deprecated
     */
    public function getEditOwnGroupmemberfields()
    {
        return $this->container['edit_own_groupmemberfields'];
    }

    /**
     * Sets edit_own_groupmemberfields
     *
     * @param bool|null $edit_own_groupmemberfields edit_own_groupmemberfields
     *
     * @return self
     * @deprecated
     */
    public function setEditOwnGroupmemberfields($edit_own_groupmemberfields)
    {
        if (is_null($edit_own_groupmemberfields)) {
            throw new \InvalidArgumentException('non-nullable edit_own_groupmemberfields cannot be null');
        }
        $this->container['edit_own_groupmemberfields'] = $edit_own_groupmemberfields;

        return $this;
    }

    /**
     * Gets edit_person_fields_of_group_members
     *
     * @return float|null
     */
    public function getEditPersonFieldsOfGroupMembers()
    {
        return $this->container['edit_person_fields_of_group_members'];
    }

    /**
     * Sets edit_person_fields_of_group_members
     *
     * @param float|null $edit_person_fields_of_group_members edit_person_fields_of_group_members
     *
     * @return self
     */
    public function setEditPersonFieldsOfGroupMembers($edit_person_fields_of_group_members)
    {
        if (is_null($edit_person_fields_of_group_members)) {
            throw new \InvalidArgumentException('non-nullable edit_person_fields_of_group_members cannot be null');
        }
        $this->container['edit_person_fields_of_group_members'] = $edit_person_fields_of_group_members;

        return $this;
    }

    /**
     * Gets edit_persons
     *
     * @return bool|null
     * @deprecated
     */
    public function getEditPersons()
    {
        return $this->container['edit_persons'];
    }

    /**
     * Sets edit_persons
     *
     * @param bool|null $edit_persons edit_persons
     *
     * @return self
     * @deprecated
     */
    public function setEditPersons($edit_persons)
    {
        if (is_null($edit_persons)) {
            throw new \InvalidArgumentException('non-nullable edit_persons cannot be null');
        }
        $this->container['edit_persons'] = $edit_persons;

        return $this;
    }

    /**
     * Gets export_group_members
     *
     * @return bool|null
     */
    public function getExportGroupMembers()
    {
        return $this->container['export_group_members'];
    }

    /**
     * Sets export_group_members
     *
     * @param bool|null $export_group_members export_group_members
     *
     * @return self
     */
    public function setExportGroupMembers($export_group_members)
    {
        if (is_null($export_group_members)) {
            throw new \InvalidArgumentException('non-nullable export_group_members cannot be null');
        }
        $this->container['export_group_members'] = $export_group_members;

        return $this;
    }

    /**
     * Gets get_emails
     *
     * @return bool|null
     */
    public function getGetEmails()
    {
        return $this->container['get_emails'];
    }

    /**
     * Sets get_emails
     *
     * @param bool|null $get_emails get_emails
     *
     * @return self
     */
    public function setGetEmails($get_emails)
    {
        if (is_null($get_emails)) {
            throw new \InvalidArgumentException('non-nullable get_emails cannot be null');
        }
        $this->container['get_emails'] = $get_emails;

        return $this;
    }

    /**
     * Gets invite_person
     *
     * @return bool|null
     */
    public function getInvitePerson()
    {
        return $this->container['invite_person'];
    }

    /**
     * Sets invite_person
     *
     * @param bool|null $invite_person invite_person
     *
     * @return self
     */
    public function setInvitePerson($invite_person)
    {
        if (is_null($invite_person)) {
            throw new \InvalidArgumentException('non-nullable invite_person cannot be null');
        }
        $this->container['invite_person'] = $invite_person;

        return $this;
    }

    /**
     * Gets mail_group_members
     *
     * @return bool|null
     */
    public function getMailGroupMembers()
    {
        return $this->container['mail_group_members'];
    }

    /**
     * Sets mail_group_members
     *
     * @param bool|null $mail_group_members mail_group_members
     *
     * @return self
     */
    public function setMailGroupMembers($mail_group_members)
    {
        if (is_null($mail_group_members)) {
            throw new \InvalidArgumentException('non-nullable mail_group_members cannot be null');
        }
        $this->container['mail_group_members'] = $mail_group_members;

        return $this;
    }

    /**
     * Gets remove_from_group
     *
     * @return bool|null
     */
    public function getRemoveFromGroup()
    {
        return $this->container['remove_from_group'];
    }

    /**
     * Sets remove_from_group
     *
     * @param bool|null $remove_from_group remove_from_group
     *
     * @return self
     */
    public function setRemoveFromGroup($remove_from_group)
    {
        if (is_null($remove_from_group)) {
            throw new \InvalidArgumentException('non-nullable remove_from_group cannot be null');
        }
        $this->container['remove_from_group'] = $remove_from_group;

        return $this;
    }

    /**
     * Gets see_group
     *
     * @return float|null
     */
    public function getSeeGroup()
    {
        return $this->container['see_group'];
    }

    /**
     * Sets see_group
     *
     * @param float|null $see_group see_group
     *
     * @return self
     */
    public function setSeeGroup($see_group)
    {
        if (is_null($see_group)) {
            throw new \InvalidArgumentException('non-nullable see_group cannot be null');
        }
        $this->container['see_group'] = $see_group;

        return $this;
    }

    /**
     * Gets see_group_member_fields
     *
     * @return float|null
     */
    public function getSeeGroupMemberFields()
    {
        return $this->container['see_group_member_fields'];
    }

    /**
     * Sets see_group_member_fields
     *
     * @param float|null $see_group_member_fields see_group_member_fields
     *
     * @return self
     */
    public function setSeeGroupMemberFields($see_group_member_fields)
    {
        if (is_null($see_group_member_fields)) {
            throw new \InvalidArgumentException('non-nullable see_group_member_fields cannot be null');
        }
        $this->container['see_group_member_fields'] = $see_group_member_fields;

        return $this;
    }

    /**
     * Gets see_group_tags
     *
     * @return bool|null
     */
    public function getSeeGroupTags()
    {
        return $this->container['see_group_tags'];
    }

    /**
     * Sets see_group_tags
     *
     * @param bool|null $see_group_tags see_group_tags
     *
     * @return self
     */
    public function setSeeGroupTags($see_group_tags)
    {
        if (is_null($see_group_tags)) {
            throw new \InvalidArgumentException('non-nullable see_group_tags cannot be null');
        }
        $this->container['see_group_tags'] = $see_group_tags;

        return $this;
    }

    /**
     * Gets see_groupmemberfields
     *
     * @return float|null
     * @deprecated
     */
    public function getSeeGroupmemberfields()
    {
        return $this->container['see_groupmemberfields'];
    }

    /**
     * Sets see_groupmemberfields
     *
     * @param float|null $see_groupmemberfields see_groupmemberfields
     *
     * @return self
     * @deprecated
     */
    public function setSeeGroupmemberfields($see_groupmemberfields)
    {
        if (is_null($see_groupmemberfields)) {
            throw new \InvalidArgumentException('non-nullable see_groupmemberfields cannot be null');
        }
        $this->container['see_groupmemberfields'] = $see_groupmemberfields;

        return $this;
    }

    /**
     * Gets see_hidden_group
     *
     * @return bool|null
     */
    public function getSeeHiddenGroup()
    {
        return $this->container['see_hidden_group'];
    }

    /**
     * Sets see_hidden_group
     *
     * @param bool|null $see_hidden_group see_hidden_group
     *
     * @return self
     */
    public function setSeeHiddenGroup($see_hidden_group)
    {
        if (is_null($see_hidden_group)) {
            throw new \InvalidArgumentException('non-nullable see_hidden_group cannot be null');
        }
        $this->container['see_hidden_group'] = $see_hidden_group;

        return $this;
    }

    /**
     * Gets see_own_group_member_fields
     *
     * @return float|null
     */
    public function getSeeOwnGroupMemberFields()
    {
        return $this->container['see_own_group_member_fields'];
    }

    /**
     * Sets see_own_group_member_fields
     *
     * @param float|null $see_own_group_member_fields see_own_group_member_fields
     *
     * @return self
     */
    public function setSeeOwnGroupMemberFields($see_own_group_member_fields)
    {
        if (is_null($see_own_group_member_fields)) {
            throw new \InvalidArgumentException('non-nullable see_own_group_member_fields cannot be null');
        }
        $this->container['see_own_group_member_fields'] = $see_own_group_member_fields;

        return $this;
    }

    /**
     * Gets see_persons
     *
     * @return float|null
     */
    public function getSeePersons()
    {
        return $this->container['see_persons'];
    }

    /**
     * Sets see_persons
     *
     * @param float|null $see_persons see_persons
     *
     * @return self
     */
    public function setSeePersons($see_persons)
    {
        if (is_null($see_persons)) {
            throw new \InvalidArgumentException('non-nullable see_persons cannot be null');
        }
        $this->container['see_persons'] = $see_persons;

        return $this;
    }

    /**
     * Gets see_tags
     *
     * @return bool|null
     */
    public function getSeeTags()
    {
        return $this->container['see_tags'];
    }

    /**
     * Sets see_tags
     *
     * @param bool|null $see_tags see_tags
     *
     * @return self
     */
    public function setSeeTags($see_tags)
    {
        if (is_null($see_tags)) {
            throw new \InvalidArgumentException('non-nullable see_tags cannot be null');
        }
        $this->container['see_tags'] = $see_tags;

        return $this;
    }

    /**
     * Gets view_history
     *
     * @return bool|null
     */
    public function getViewHistory()
    {
        return $this->container['view_history'];
    }

    /**
     * Sets view_history
     *
     * @param bool|null $view_history view_history
     *
     * @return self
     */
    public function setViewHistory($view_history)
    {
        if (is_null($view_history)) {
            throw new \InvalidArgumentException('non-nullable view_history cannot be null');
        }
        $this->container['view_history'] = $view_history;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


