<?php
/**
 * PersonPrivacyPolicyOwner
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  ChurchTools
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ChurchTools REST API
 *
 * The ChurchTools REST API is the best entry point for developers to access ChurchTools. <br><br> **Authentication:** You need to be authorized to use some endpoints. Those endpoints are marked by a gray lock symbol. If you view the documentation, while you are logged into ChurchTools, all requests are already authorized. If you want to authorized a request, you need to provide a `Login Token` as `Authorization` header in the format `Authorization: Login <token>` or send a valid cookie. You can use the green \"Authorize\" dialog to enter those details and see how a request would look like in detail. <br><br> **Missing Endpoints:** Not all features are yet available by our new REST API. This documentation will grow in the future. We are working hard to add new endpoints with every ChurchTools version. The documentation will always show only those endpoints you can use with your ChurchTools installation.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@churchtools.de
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ChurchTools\Model;

use \ArrayAccess;
use \ChurchTools\ObjectSerializer;

/**
 * PersonPrivacyPolicyOwner Class Doc Comment
 *
 * @category Class
 * @package  ChurchTools
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PersonPrivacyPolicyOwner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PersonPrivacyPolicy_owner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'accepted' => 'bool',
        'accepted_date' => '\DateTime',
        'accepted_type' => 'string',
        'accepted_who' => 'int',
        'age' => 'int',
        'allowed_to_accept' => 'bool',
        'edit_birthday' => 'bool',
        'first_name' => 'string',
        'id' => 'int',
        'image_url' => 'string',
        'last_name' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'accepted' => null,
        'accepted_date' => 'date-time',
        'accepted_type' => null,
        'accepted_who' => null,
        'age' => null,
        'allowed_to_accept' => null,
        'edit_birthday' => null,
        'first_name' => null,
        'id' => null,
        'image_url' => null,
        'last_name' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'accepted' => false,
        'accepted_date' => false,
        'accepted_type' => false,
        'accepted_who' => false,
        'age' => false,
        'allowed_to_accept' => false,
        'edit_birthday' => false,
        'first_name' => false,
        'id' => false,
        'image_url' => false,
        'last_name' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'accepted' => 'accepted',
        'accepted_date' => 'acceptedDate',
        'accepted_type' => 'acceptedType',
        'accepted_who' => 'acceptedWho',
        'age' => 'age',
        'allowed_to_accept' => 'allowedToAccept',
        'edit_birthday' => 'editBirthday',
        'first_name' => 'firstName',
        'id' => 'id',
        'image_url' => 'imageUrl',
        'last_name' => 'lastName'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'accepted' => 'setAccepted',
        'accepted_date' => 'setAcceptedDate',
        'accepted_type' => 'setAcceptedType',
        'accepted_who' => 'setAcceptedWho',
        'age' => 'setAge',
        'allowed_to_accept' => 'setAllowedToAccept',
        'edit_birthday' => 'setEditBirthday',
        'first_name' => 'setFirstName',
        'id' => 'setId',
        'image_url' => 'setImageUrl',
        'last_name' => 'setLastName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'accepted' => 'getAccepted',
        'accepted_date' => 'getAcceptedDate',
        'accepted_type' => 'getAcceptedType',
        'accepted_who' => 'getAcceptedWho',
        'age' => 'getAge',
        'allowed_to_accept' => 'getAllowedToAccept',
        'edit_birthday' => 'getEditBirthday',
        'first_name' => 'getFirstName',
        'id' => 'getId',
        'image_url' => 'getImageUrl',
        'last_name' => 'getLastName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('accepted', $data ?? [], null);
        $this->setIfExists('accepted_date', $data ?? [], null);
        $this->setIfExists('accepted_type', $data ?? [], null);
        $this->setIfExists('accepted_who', $data ?? [], null);
        $this->setIfExists('age', $data ?? [], null);
        $this->setIfExists('allowed_to_accept', $data ?? [], null);
        $this->setIfExists('edit_birthday', $data ?? [], null);
        $this->setIfExists('first_name', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('image_url', $data ?? [], null);
        $this->setIfExists('last_name', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['accepted'] === null) {
            $invalidProperties[] = "'accepted' can't be null";
        }
        if ($this->container['accepted_type'] === null) {
            $invalidProperties[] = "'accepted_type' can't be null";
        }
        if ($this->container['age'] === null) {
            $invalidProperties[] = "'age' can't be null";
        }
        if ($this->container['allowed_to_accept'] === null) {
            $invalidProperties[] = "'allowed_to_accept' can't be null";
        }
        if ($this->container['edit_birthday'] === null) {
            $invalidProperties[] = "'edit_birthday' can't be null";
        }
        if ($this->container['first_name'] === null) {
            $invalidProperties[] = "'first_name' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['image_url'] === null) {
            $invalidProperties[] = "'image_url' can't be null";
        }
        if ($this->container['last_name'] === null) {
            $invalidProperties[] = "'last_name' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets accepted
     *
     * @return bool
     */
    public function getAccepted()
    {
        return $this->container['accepted'];
    }

    /**
     * Sets accepted
     *
     * @param bool $accepted accepted
     *
     * @return self
     */
    public function setAccepted($accepted)
    {
        if (is_null($accepted)) {
            throw new \InvalidArgumentException('non-nullable accepted cannot be null');
        }
        $this->container['accepted'] = $accepted;

        return $this;
    }

    /**
     * Gets accepted_date
     *
     * @return \DateTime|null
     */
    public function getAcceptedDate()
    {
        return $this->container['accepted_date'];
    }

    /**
     * Sets accepted_date
     *
     * @param \DateTime|null $accepted_date A timestamp in Zulu time format, e.g. '2022-10-19T12:00:00Z'
     *
     * @return self
     */
    public function setAcceptedDate($accepted_date)
    {
        if (is_null($accepted_date)) {
            throw new \InvalidArgumentException('non-nullable accepted_date cannot be null');
        }
        $this->container['accepted_date'] = $accepted_date;

        return $this;
    }

    /**
     * Gets accepted_type
     *
     * @return string
     */
    public function getAcceptedType()
    {
        return $this->container['accepted_type'];
    }

    /**
     * Sets accepted_type
     *
     * @param string $accepted_type accepted_type
     *
     * @return self
     */
    public function setAcceptedType($accepted_type)
    {
        if (is_null($accepted_type)) {
            throw new \InvalidArgumentException('non-nullable accepted_type cannot be null');
        }
        $this->container['accepted_type'] = $accepted_type;

        return $this;
    }

    /**
     * Gets accepted_who
     *
     * @return int|null
     */
    public function getAcceptedWho()
    {
        return $this->container['accepted_who'];
    }

    /**
     * Sets accepted_who
     *
     * @param int|null $accepted_who accepted_who
     *
     * @return self
     */
    public function setAcceptedWho($accepted_who)
    {
        if (is_null($accepted_who)) {
            throw new \InvalidArgumentException('non-nullable accepted_who cannot be null');
        }
        $this->container['accepted_who'] = $accepted_who;

        return $this;
    }

    /**
     * Gets age
     *
     * @return int
     */
    public function getAge()
    {
        return $this->container['age'];
    }

    /**
     * Sets age
     *
     * @param int $age age
     *
     * @return self
     */
    public function setAge($age)
    {
        if (is_null($age)) {
            throw new \InvalidArgumentException('non-nullable age cannot be null');
        }
        $this->container['age'] = $age;

        return $this;
    }

    /**
     * Gets allowed_to_accept
     *
     * @return bool
     */
    public function getAllowedToAccept()
    {
        return $this->container['allowed_to_accept'];
    }

    /**
     * Sets allowed_to_accept
     *
     * @param bool $allowed_to_accept allowed_to_accept
     *
     * @return self
     */
    public function setAllowedToAccept($allowed_to_accept)
    {
        if (is_null($allowed_to_accept)) {
            throw new \InvalidArgumentException('non-nullable allowed_to_accept cannot be null');
        }
        $this->container['allowed_to_accept'] = $allowed_to_accept;

        return $this;
    }

    /**
     * Gets edit_birthday
     *
     * @return bool
     */
    public function getEditBirthday()
    {
        return $this->container['edit_birthday'];
    }

    /**
     * Sets edit_birthday
     *
     * @param bool $edit_birthday edit_birthday
     *
     * @return self
     */
    public function setEditBirthday($edit_birthday)
    {
        if (is_null($edit_birthday)) {
            throw new \InvalidArgumentException('non-nullable edit_birthday cannot be null');
        }
        $this->container['edit_birthday'] = $edit_birthday;

        return $this;
    }

    /**
     * Gets first_name
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->container['first_name'];
    }

    /**
     * Sets first_name
     *
     * @param string $first_name first_name
     *
     * @return self
     */
    public function setFirstName($first_name)
    {
        if (is_null($first_name)) {
            throw new \InvalidArgumentException('non-nullable first_name cannot be null');
        }
        $this->container['first_name'] = $first_name;

        return $this;
    }

    /**
     * Gets id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param int $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets image_url
     *
     * @return string
     */
    public function getImageUrl()
    {
        return $this->container['image_url'];
    }

    /**
     * Sets image_url
     *
     * @param string $image_url image_url
     *
     * @return self
     */
    public function setImageUrl($image_url)
    {
        if (is_null($image_url)) {
            throw new \InvalidArgumentException('non-nullable image_url cannot be null');
        }
        $this->container['image_url'] = $image_url;

        return $this;
    }

    /**
     * Gets last_name
     *
     * @return string
     */
    public function getLastName()
    {
        return $this->container['last_name'];
    }

    /**
     * Sets last_name
     *
     * @param string $last_name last_name
     *
     * @return self
     */
    public function setLastName($last_name)
    {
        if (is_null($last_name)) {
            throw new \InvalidArgumentException('non-nullable last_name cannot be null');
        }
        $this->container['last_name'] = $last_name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


